openapi: 3.0.0
servers:
  - url: 'https://api.hivemc.com/v1'
info:
  description: ''
  version: 1.0.0
  title: HiveMc API
  contact: {}
paths:
  '/player/{nameOrUuid}':
    $ref: './paths/player/index.yaml'
  '/games':
    $ref: './paths/games.yaml'
