openapi: 3.0.0
servers:
  - url: 'https://api.hivemc.com/v1'
info:
  description: ''
  version: 1.0.0
  title: HiveMc API
  contact: {}
paths:
  '/player/{nameOrUuid}':
    $ref: './paths/player/index.yaml'
  
  '/game':
    $ref: './paths/games.yaml'

  '/game/{game-id}':
    $ref: './paths/game/index.yaml'

  '/game/{game-id}/maps':
    $ref: './paths/game/maps.yaml'
  '/game/{game-id}/maps/{map-id}':
    $ref: './paths/game/map.yaml'

  '/game/SG/data/{game-id}':
    $ref: './paths/game/SG/data.yaml'
  '/game/SG/data/{game-id}/{player-uuid}':
    $ref: './paths/game/SG/dataPlayer.yaml'

