openapi: 3.0.0
servers:
  - url: 'https://api.hivemc.com/v1'
info:
  description: ''
  version: 1.0.0
  title: HiveMC API
  contact: {}
paths:
  '/player/{uuid-or-name}':
    $ref: './paths/player/index.yaml'
  
  '/player/{uuid-or-name}/status/raw':
    $ref: './paths/player/status-raw.yaml'
  
  '/player/{uuid-or-name}/status':
    $ref: './paths/player/status.yaml'

  '/player/{uuid-or-name}/{game}':
    $ref: './paths/player/game.yaml'



  '/game':
    $ref: './paths/games.yaml'

  '/game/{game-id}':
    $ref: './paths/game/index.yaml'

  '/game/{game-id}/maps':
    $ref: './paths/game/maps.yaml'
  '/game/{game-id}/maps/{map-id}':
    $ref: './paths/game/map.yaml'

  '/game/{game-id}/titles':
    $ref: './paths/game/titles.yaml'



  '/game/{game-id}/leaderboard/{start}/{end}':
    $ref: './paths/game/leaderboard.yaml'

  '/game/SG/data/{game-id}':
    $ref: './paths/game/SG/data.yaml'
  '/game/SG/data/{game-id}/{player-uuid}':
    $ref: './paths/game/SG/dataPlayer.yaml'



  '/server/playercount':
    $ref: './paths/server/playercount.yaml'
  '/server/uniquecount':
    $ref: './paths/server/uniquecount.yaml'

  '/server/achievements':
    $ref: './paths/server/achievements.yaml'
  '/server/trophies':
    $ref: './paths/server/trophies.yaml'

  '/server/ranks':
    $ref: './paths/server/ranks.yaml'


  '/staff':
    $ref: './paths/staff.yaml'

